const subObject = {
  id: "sub_1NWRFv2eZvKYlo2C3VSxqCBc",
  object: "subscription",
  application: null,
  application_fee_percent: null,
  automatic_tax: {
    enabled: false,
  },
  billing_cycle_anchor: 1689976379,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: 1689976382,
  cancellation_details: {
    comment: null,
    feedback: null,
    reason: "cancellation_requested",
  },
  collection_method: "charge_automatically",
  created: 1689976379,
  currency: "usd",
  current_period_end: 1692654779,
  current_period_start: 1689976379,
  customer: "cus_OJ3MK3zCQMQOC9",
  days_until_due: null,
  default_payment_method: "pm_1NWRFu2eZvKYlo2CNLwMKLvR",
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  ended_at: 1689976382,
  items: {
    object: "list",
    data: [
      {
        id: "si_OJ3MSeyJU3N0gI",
        object: "subscription_item",
        billing_thresholds: null,
        created: 1689976380,
        metadata: {},
        price: {
          id: "price_1NWRFH2eZvKYlo2C6lCmC5k8",
          object: "price",
          active: true,
          billing_scheme: "per_unit",
          created: 1689976339,
          currency: "usd",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_OJ3LHtynvbhvjA",
          recurring: {
            aggregate_usage: null,
            interval: "month",
            interval_count: 1,
            usage_type: "licensed",
          },
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "recurring",
          unit_amount: 2999,
          unit_amount_decimal: "2999",
        },
        quantity: 1,
        subscription: "sub_1NWRFv2eZvKYlo2C3VSxqCBc",
        tax_rates: [],
      },
    ],
    has_more: false,
    url: "/v1/subscription_items?subscription=sub_1NWRFv2eZvKYlo2C3VSxqCBc",
  },
  latest_invoice: "in_1NWRFv2eZvKYlo2C5EJpan9j",
  livemode: false,
  metadata: {
    OrgStoreId: "33333333-3333-3333-3333-333333333333",
    OrgDeviceId: "00000000-0000-0000-0000-000000000000",
    Vehicles: "33333333-3333-3333-3333-333333333333",
    CustomerId: "22222222-2222-2222-2222-222222222222",
    OrgOrderId: "d47ba95e-e080-4120-831e-3fe46d6e02c8",
  },
  next_pending_invoice_item_invoice: null,
  on_behalf_of: null,
  pause_collection: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: null,
    save_default_payment_method: "off",
  },
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  schedule: null,
  start_date: 1689976379,
  status: "canceled",
  test_clock: null,
  transfer_data: null,
  trial_end: null,
  trial_settings: {
    end_behavior: {
      missing_payment_method: "create_invoice",
    },
  },
  trial_start: null,
};

const invObject = {
  id: "in_1NWebx2eZvKYlo2CZMujWY3r",
  object: "invoice",
  account_country: "US",
  account_name: "Stripe.com",
  account_tax_ids: null,
  amount_due: 299,
  amount_paid: 0,
  amount_remaining: 299,
  amount_shipping: 0,
  application: null,
  application_fee_amount: null,
  attempt_count: 0,
  attempted: false,
  auto_advance: false,
  automatic_tax: {
    enabled: false,
    status: null,
  },
  billing_reason: "manual",
  charge: null,
  collection_method: "charge_automatically",
  created: 1690027717,
  currency: "usd",
  custom_fields: null,
  customer: "cus_9s6XKzkNRiz8i3",
  customer_address: null,
  customer_email: null,
  customer_name: null,
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: "none",
  customer_tax_ids: [],
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  description: null,
  discount: null,
  discounts: [],
  due_date: null,
  effective_at: null,
  ending_balance: null,
  footer: null,
  from_invoice: null,
  hosted_invoice_url: null,
  invoice_pdf: null,
  last_finalization_error: null,
  latest_revision: null,
  lines: {
    object: "list",
    data: [
      {
        id: "il_1NWebx2eZvKYlo2Cuio0i9rb",
        object: "line_item",
        amount: 299,
        amount_excluding_tax: 299,
        currency: "usd",
        description: "My First Invoice Item (created for API docs)",
        discount_amounts: [],
        discountable: true,
        discounts: [],
        invoice_item: "ii_1NWebx2eZvKYlo2COEScIzaF",
        livemode: false,
        metadata: {},
        period: {
          end: 1690027717,
          start: 1690027717,
        },
        price: {
          id: "price_1NWc702eZvKYlo2CpfLx5s2K",
          object: "price",
          active: true,
          billing_scheme: "per_unit",
          created: 1690018110,
          currency: "usd",
          custom_unit_amount: null,
          livemode: false,
          lookup_key: null,
          metadata: {},
          nickname: null,
          product: "prod_OJEakTr1gEbbWb",
          recurring: null,
          tax_behavior: "unspecified",
          tiers_mode: null,
          transform_quantity: null,
          type: "one_time",
          unit_amount: 299,
          unit_amount_decimal: "299",
        },
        proration: false,
        proration_details: {
          credited_items: null,
        },
        quantity: 1,
        subscription: null,
        tax_amounts: [],
        tax_rates: [],
        type: "invoiceitem",
        unit_amount_excluding_tax: "299",
      },
    ],
    has_more: false,
    url: "/v1/invoices/in_1NWebx2eZvKYlo2CZMujWY3r/lines",
  },
  livemode: false,
  metadata: {},
  next_payment_attempt: null,
  number: null,
  on_behalf_of: null,
  paid: false,
  paid_out_of_band: false,
  payment_intent: null,
  payment_settings: {
    default_mandate: null,
    payment_method_options: null,
    payment_method_types: null,
  },
  period_end: 1688482163,
  period_start: 1688395763,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  quote: null,
  receipt_number: null,
  redaction: null,
  rendering_options: null,
  shipping_cost: null,
  shipping_details: null,
  starting_balance: 0,
  statement_descriptor: null,
  status: "draft",
  status_transitions: {
    finalized_at: null,
    marked_uncollectible_at: null,
    paid_at: null,
    voided_at: null,
  },
  subscription: null,
  subtotal: 299,
  subtotal_excluding_tax: 299,
  tax: null,
  test_clock: null,
  total: 299,
  total_discount_amounts: [],
  total_excluding_tax: 299,
  total_tax_amounts: [],
  transfer_data: null,
  webhooks_delivered_at: null,
};

module.exports = { subObject, invObject };
