const CONFIG = {
    PUBLISHABLE_KEY : "pk_test_51M4ns1SBx6KtlGUSdnIZL9ehhRylPddDkOoWuIl1DGLDHXm9FR4C3CSjNB9KOWgVLSJiKNbylvPl8s3s7dDtYJg200FK52NvMb",
    SECERET_KEY : "sk_test_51M4ns1SBx6KtlGUSzXVJ1BfmMamXHCBhBTLB5PQ3c4TVSMzQwOBcfOdv7dUgjbhSTuRxOHBOF2MPWk5oj7fUsACT00OvFSbBEn",
    CUSTOMER_ID : "cus_Nuvr1bOpJ7nzY6",
    PRODUCT_ID :"",
    PRICE_ID :"price_1NWYA0SBx6KtlGUSWJNe8qii",
}

module.exports = CONFIG